### ISSUE TITLE
Перед тем как начать

### ISSUE THREAD

**Issue by Vlad160** [DunaevViktor/PoetryPortal#14]
Перед тем как начать стоило бы немного разобраться с чем мы работаем. Есть документация переведенная на русский язык
https://abraxabra.ru/react.js/
https://learn-reactjs.ru/tutorial
Все смотреть не надо. Все постепенно. 
В отдельной ветке проделай вот такие шаги (сделаешь PR, но мержить не будем).
1) Сейчас у нас очень много файлов в src, назначение которых непонятно. Удаляем все в src, ибо нехер там быть тому, что мы не понимаем.
2) Делаем ```npm start```.
3) Белый экран. Ничего удивительного, мы же все удалили.
4) Добавляем в src файлик index.js. Он особенный, это входная точка в приложение. Так заложено рект скриптами.
5) Делим работу на 3 части.
5.1) Как-то нужно подключить реакт в этот самый index.js, чтобы произошла вся магия. Тут приходит на помощью ключевое слово import. import это новый стандарт javascript, который позволят подключать один файл к другому. Импорты бывают разные: default, named, namespace. Погугли и попробуй разобраться. Не получится - спрашивай. 
```
import React from 'react';
import ReactDOM from 'react-dom';
```
Эти две строчки делают то, что мы хотели. Реакт у нас уже есть, но экран все ещё белый. Переходим ко второму шагу.
5.2) В реакте используется компонентный подход. Каждый элемент твоего приложения - компонент.
Для примера можно взять один стих. Стих с текстом, описанием и автором - компонет. Как дробить на компоненты приходит с опытом. Компоненты можно рисовать двумя способами.
```
const Block = function () {
return <div>Ky!</div>
}

class Block extends React.Component {
render() {
 return <div>Ky!</div>
}
}

```
Каждый компонет должен вернуть валидный JSX (о нем позже). Так какой же способ использовать? 
Идем и читаем stateless statefull components React
Предположим, что мы взяли первый вариант с функцией.
5.3) Осталось немного. Последнее, что нам нужно сделать, так это сказать реакту, где же отправная точка нашего приложения. Взглянем на index.html и исследуем его. Есть там какой-то id="root".
По умолчанию реакт ждет, что это и будет отправная точка приложения. Так давай же скормим ему это!
```
ReactDOM.render(
Block,
document.querySelector('#root')
)
```
Проверяем результат.
Информации много. Теперь пару заданий.

1) Что такое JSX? Что такое babel? https://babeljs.io/repl
2) Почему констркция не работает? Как исправить
```
const Block = function () {
return
 <div>Ky!</div>
}
```
3) Переведи такой html в валидный jsx:
```
<div class="biba">
<label for="input" type="text"/>
<button style="background-color="red">Click me!</button>
</div>
```
Сюда же экстра задание. Сделай так, чтобы вместо "Click me!" была переменная, которую ты объявишь в компоненте.

Вопросы можешь задавать сюда.

**Comment by Vlad160** [comment]
Отдельно.
В чем разница между React и ReactDOM? Мы же вроде просто на реакте пишем.

**Comment by Vlad160** [comment]
И ещё один совет. Консоль в браузере должна быть открыта всегда! f12 в хроме

**Comment by ViktarDunayeu** [comment]
1) Я не понимаю зачем переписывать код с ES6 на ES5 ? Если ES6 не поддерживается полностью браузерами , зачем на нем писать?
2) И вопрос по default, named, namespace import
**а)** как я понял мы использовали default, например тут:
`import logo from './logo.svg';`
и по идее вместо logo можно использовать любое имя?
**б)** а если бы нам нужна была переменная `a` из файла `b.js`, то использовался бы named import?
`import a from './b.js';`

**Comment by r-karol** [comment]
ES6 уже подерживается почти всеми, а чтобы поддерживался всеми используется babel. Babel компилирует ES6 в ES5. ES6 принес много классных фишек, таких как лямбды, деструктуризация, промисы да и вообще кучу всего. Они делают разработку гораздо приятнее и даже быстрее, поэтому и используют.
`import logo from './logo.svg';` - это и правда синтаксис дефолтного импорта. Второй пример, который ты приводишь в вопросе, ничем не отличается от этого, так что это один и тот же тип импорта. Второй ответ [тут](https://stackoverflow.com/questions/42478661/difference-between-export-and-export-default-in-javascript) должен прояснить. Создай два js файлика и попробуй все виды.

**Comment by r-karol** [comment]
И еще посмотри как index.js использует App компоненту

**Comment by Vlad160** [comment]
> 1. Я не понимаю зачем переписывать код с ES6 на ES5 ? Если ES6 не поддерживается полностью браузерами , зачем на нем писать?
> 2. И вопрос по default, named, namespace import
>    **а)** как я понял мы использовали default, например тут:
>    `import logo from './logo.svg';`
>    и по идее вместо logo можно использовать любое имя?
>    **б)** а если бы нам нужна была переменная `a` из файла `b.js`, то использовался бы named import?
>    `import a from './b.js';`

Почти так. Когда у тебя default, то импорт можно сделать под любым именем. Файл не может иметь более одного default импорта, что логично, иначе как понять что именно импортитися.
Named чуть по-другому
```import { App } from './App';```
Отличние - фигруные скобки. Здесь как раз и надо, чтобы имена совпадали. Об этом чуть позже все расскажу
