### ISSUE TITLE
Создай на хероку приложение для master ветки

### ISSUE THREAD

**Issue by r-karol** [DunaevViktor/PoetryPortal#16]
Имя которое надо дать приложению смотри [тут](https://github.com/DunaevViktor/PoetryPortal/blob/dev/.travis.yml)

**Comment by r-karol** [comment]
Скрин сюда скинь как сделаешь

**Comment by ViktarDunayeu** [comment]
![default](https://user-images.githubusercontent.com/25617899/52065789-4aaad380-2588-11e9-91a8-e071bcdb3290.png)
мне нужно его как то настраивать?

**Comment by r-karol** [comment]
Не, все кул
