### ISSUE TITLE
Структура сайта

### ISSUE THREAD

**Issue by r-karol** [DunaevViktor/PoetryPortal#17]
Какая будет структура сайта?
1. Сколько будет страниц и какие?
2. Хедер с менюшкой будет присутсвовать на всех из этих страниц?
3. Будет ли футер?
4. Будет ли что-то еще, кроме хедера, контейнера, в котором лежит все специфическое для страницы (и футера, если будет)?
Это просто для уточнения требований, делать ничего не надо, в комменты пиши.

**Comment by ViktarDunayeu** [comment]
1. Три (возможно четыре) типа страниц:

- главная страница (выглядит примерно как самый последний мокап);

- страница "обо мне";

- страница "добавление поста"/"добавление отзыва" (по структуре и смыслу похожие страницы, только с немного отличающимися формами);

- отдельная страница для каждого стиха, что-то типа развернуть статью (не уверен, что нужен такой тип, т.к. стихи не большие и поместятся полностью на главной, но в идеале, когда стихов будем много, чтобы бесконечно не листать главную , можно на ней постить только по строфе и добавить "читать далее", тогда эта страница актуальна).

2. Хэдер на всех страницах.

3.Футер будет (приблизительно с таким функционалом как в последнем мокапе).

4.Что-то еще не планирую.

**Comment by r-karol** [comment]
Главная - список всех публикаций, как я понимаю. Будет пагинация или инфинит скрол?
Футер будет закреплен внизу экрана, или на дне странички?
Страничка отзыва? Может просто коменты прикрутим на страницу детального просмотоа?

**Comment by ViktarDunayeu** [comment]
1. Мне больше нравится infinite scroll;

2. Футер закреплен на дне странички , а хэдер хочу вверху экрана, с infinite scroll-ом мне кажется это логично;

3. Я не знаю насколько сложно реализовать систему комментов, если это просто грубо говоря добавление элемента в card , то лучше комменты.

**Comment by r-karol** [comment]
Для комментов может быть просто плагин подрубим
