### ISSUE TITLE
Перед тем как начать [2]

### ISSUE THREAD

**Issue by Vlad160** [DunaevViktor/PoetryPortal#20]
Последнее задание, перед тем как приступить к реализации твоего проекта. Это задание будет побольше, а значит, интереснее.
В этом задании мы сделаем небольшой список заданий (очень оригинально да)
Можешь продолжить в той же ветке, можешь создать новую.
Суть задания получить что-то типо такого:
![image](https://user-images.githubusercontent.com/21972165/52196810-44f60c00-286e-11e9-917a-b6777a6b88df.png)
Только аккуратнее и лучше стилизованное.
Здесь мы познакомимся с conditional rendering, statefull components, научимся делить функциональность между компонентами и научимся передавать данные в компоненты.
1) Создадим файлик ```TodoItem.js``` (по соглашениям в комьюнити их принято называть с большой буквы) 
В этой компоненте применим старый способ с функциями.
Начнем с:
```
const TodoItem = (props) => {
return <div>props.item.text</div>
}
```
Тут есть что-то новенькое. Во-первых, arrow function (думаю ты знаком, но можно почитать тут https://learn.javascript.ru/es-function). Во-вторых, какие-то props. Эти props есть ни что иное, как данные переданные в компоненту. Их принято называть props. Читаем тут: https://learn-reactjs.ru/basics/components-and-props
Эта компонента будет представлять собой один экземпляр списка дел. Т.к. статусы должны быть разными цветами, тот тут и будет conditional rendering (читаем https://learn-reactjs.ru/basics/conditional-rendering)
 Теперь надо дать возможность всем остальным компонентам пользоваться этой компнентой. Для этого допишем строчку
```
export default TodoItem;
```
Делать дефолтные экспорты популярная практика в реакте. Можно написать просто ```export TodoItem``` (вспоминай как разница)
2) Теперь сделаем TodoList.js
Начнем с того, что сделаем import нашей компоненты TodoItem . Он зависит от типа экспорта, который ты использовал (либо ```import TodoItem from './TodoItem';``` либо ```import { TodoItem } from './TodoItem';```
Тут уже мы будем использовать es6 классы, для компоненты (для начала читай тут https://learn-reactjs.ru/basics/state-and-lifecycle)
Начнем с:
```
class TodoList extends React.Component {
  constructor() {
    super();
    this.state = {
      todos: [
        {
          date: new Date(),
          status: 'Сделать',
          text: 'Покормить кота'
        },
        {
          date: new Date(),
          status: 'Готово',
          text: 'Катнуть в доту'
        },
      ]
    };
  }

  render() {
    const todos = this.state.todos;
    return (
      <div>
      <div>
      <input type="text"/>
      <button>Добавить</button>
      </div>
       <ul>
       {todos.map((item, i) => <li key={i}><TodoItem item={item}/></li>)}
       </ul>
      </div>
    );
  }
}
```
Что за магический ```key``` читаем тут:  https://learn-reactjs.ru/basics/lists-and-keys
3) Осталось последнее, дать возможность самому добавлять задания.
Тут оставлю тебе только ссылки, если не разберешься - пиши, решим вместе. 
https://learn-reactjs.ru/basics/handling-events
https://learn-reactjs.ru/basics/forms
https://medium.com/@abraztsov/refs-%D0%B2-react-%D0%B2%D1%81%D1%91-%D1%87%D1%82%D0%BE-%D0%BD%D1%83%D0%B6%D0%BD%D0%BE-%D0%B7%D0%BD%D0%B0%D1%82%D1%8C-266a979690f8

В качестве бонусного задания предлагаю сделать возможность менять статус у задания (с Сделать на Готов и наоборот)
Задавай вопросы если что-нибудь хоть чуточку непонятно. Удачи!

**Comment by Vlad160** [comment]
Кстати, а в почему мы пишем:
```import TodoItem from './TodoItem';```
А не
```import TodoItem from 'TodoItem';```
Ведь реакт мы импортируем именно так

**Comment by ViktarDunayeu** [comment]
Код `import TodoItem from './TodoItem';` говорит о том, что мы будем импортировать файл локально из директории проекта, а код `import TodoItem from 'TodoItem';` о том, что файл загружается с удаленного сервера (через `npm install` и `package.json` )?

**Comment by Vlad160** [comment]
> Код `import TodoItem from './TodoItem';` говорит о том, что мы будем импортировать файл локально из директории проекта, а код `import TodoItem from 'TodoItem';` о том, что файл загружается с удаленного сервера (через `npm install` и `package.json` )?

Не совсем так. Первая часть верная, а вот вторая ненмого ошибочная. 
```
import TodoItem from 'TodoItem';
```
говорит, что мы импортируем ```TodoItem``` из папки ```node_modules/TodoItem```. Дальше там тоже идет некоторая работа. Подробнее тут: https://habr.com/ru/post/233827/ (считай, что require это import)

**Comment by Vlad160** [comment]
Есть ещё один тонкий момент. У тебя каждая компонента имеет свой набор стилей. Может случиться, что в разных компонетах стили будут называться одинаково (типо `.container {...`) и стили начнут друг на друга накладываться. Как избежать такой проблемы?
1) Можно стили называть по принципу: ${имя-компоненты}-${название стиля}
2) Этот вариант более удобен при использовании препроцессров таких как SASS. Компонета оборачивается в какой-то класс:
```
<div className="my-comp">
...
</div>
```
А далее уже в стилях писать:
```
.my-comp .container {
...
}
```
Если бы использовался препроцессор, то было бы вот так:
```
.my-comp {
// пошли все стили
}
```
Препроцессоры будут отдельной темой. Пока реши какой вариант тебе удобнее:
1) ```.my-comp-container { ... }```
2) ```.my-comp .container { ... }```
