### ISSUE TITLE
Всплытие событий

### ISSUE THREAD

**Issue by Vlad160** [DunaevViktor/PoetryPortal#21]
Вчера обнаружили, что ты не до конца понимаешь как работает обработка и всплытие событий. Рекомендую почитать эту статью https://learn.javascript.ru/event-bubbling
Как разберешься, то сделай вот такой вот примерчик
![bubbling](https://user-images.githubusercontent.com/21972165/52398378-e2994780-2ac9-11e9-8e06-a77ae84c78fe.gif)
Как вешать обработку событий, рисовать прямоугольники, надеюсь ты знаешь. Обрабоку событий сделать двумя способами: через addEventListener и в html'е (типо onclick на сам элемент). Не надо делать два разных варианта задания, просто на один элемент повесить прямо в html'е, а остальные через addEventListener 
Делать можешь где угодно, хоть на https://jsfiddle.net/

**Comment by ViktarDunayeu** [comment]
https://jsfiddle.net/SystemWIKI/fz4178Lb/16/

Работает как у тебя, но походу я слишком сложно сделал 😶

**Comment by r-karol** [comment]
не, все четко

**Comment by Vlad160** [comment]
Нормально. Главное, чтобы ты разобрался
