### ISSUE TITLE
Добавляем загрузку данных

### ISSUE THREAD

**Issue by r-karol** [DunaevViktor/PoetryPortal#30]
Создай папочку `services`, в ней `apiService.js`. В файле класс `ApiService`, создай его объект и экспортни как константу. Это будет сервис который будет получать данные с бэкенда.
Сделай у него метод `getPostsPage`.
Он будет принимать объект
```
{
    skip: number,
    take: number
}
```
Возвращать будет промис с объектом такого формата:
```
{
    skipped: number
    taken: number,
    total: number,
    items: []Post
}
```
`Post` - твой объект поста. В него добавляй все что считаешь нужным (скинь только в коменты формат для утверждения)
В этом же файле храни пока что массив захардкоженных постов и напиши реализацию метода (с учетом входных параметров). Сделай хотя бы 30 постов в массиве. И сделай так чтобы этот массив лежал в конце файла.

**Comment by r-karol** [comment]
В будущем этот класс будет запрашивать их с бэкенда

**Comment by ViktarDunayeu** [comment]
```
Post = [
{
  id: 0,
  title: "Поворотам судьбы",
  createdAt: "26-02-2019",
  author: "Виктор Дунаев",
  tags: ["философия", "разное"],
  content: "Странно, но больны на всю голову, Неожиданные повороты судьбы."
}
];
```

**Comment by r-karol** [comment]
Гуд
Подумай еще нужен ли тебе автор (если будешь только ты писать)
И content может быть нужно делать не просто текстом, а html или markdown, потому что может возникнуть проблема с переносами на следующую строку (чтобы в форме стихотворения был текст)
А еще подумай будут ли тут только стихи
если не только стихи, то может имеет смысл сделать отдельно поле 'preview' или типа того и не грузить весь контент на список (так как если не только стихи, то может много данных грузиться), а на детальный просмотр грузить с контентом (полным)
