### ISSUE TITLE
Нарисуй мокапы

### ISSUE THREAD

**Issue by r-karol** [DunaevViktor/PoetryPortal#4]
Нарисуй мокапы в каком-нибудь предназначенном для этого сервисе. Не надо их делать слишком подробными, так, просто чтобы прикинуть как примерно будет выглядеть. Только сначала выбери библиотеку компонент которую будем использовать и под нее мокапы рисуй. И старайся максимально пользоваться тем что предоставляет библиотека (когда будешь придумывать дизайн). То есть старайся собрать конструктор из того, что предоставляет библиотека

**Comment by ViktarDunayeu** [comment]
1. https://yapx.ru/v/DQTqG
2. https://yapx.ru/v/DQTvU
3. https://yapx.ru/v/DQTy5
**У мокапов есть описание!**

**Comment by r-karol** [comment]
Все странички сделаны в очень авторском дизайне, а форма для создания - исходя из какой-то библиотеки. Может как-нибудь подвести под общий знаменатель? Или это просто мокапы и так и оставим?

**Comment by r-karol** [comment]
Может менюшку слева перенести наверх? В хедер. Она маленькая, там всего три пункта, при этом она съедает четверть странички так как вертикально на странице расположена. Что думаете?
Как в твиттере, например
![image](https://user-images.githubusercontent.com/17727164/51922464-23260080-23fa-11e9-8116-5144d7b850cf.png)

**Comment by ViktarDunayeu** [comment]
В идеале я хочу, чтобы форма создания была на подобие этой (прозрачная),а на background нейтральная картинка в светлых тонах(не хочу делать заливку просто цветом)
https://mdbootstrap.com/previews/docs/latest/html/intros/intro-register-classic-form.html#

**Comment by ViktarDunayeu** [comment]
насчет кнопок согласен, теперь мне надо подумать что слева разместить , если будет только колонка "Популярные" , ей много места , возможно добавлю архив блога 
![default](https://user-images.githubusercontent.com/25617899/51922847-e73f6b00-23fa-11e9-937a-56f8f9911468.png)

**Comment by r-karol** [comment]
[Такая](https://github.com/DunaevViktor/PoetryPortal/issues/4#issuecomment-458602323) форма неудобная для введения большого количества текста. Скорее всего, мы используем какой-нибудь Markdown-editor ([Типа вот такой штуки](https://draftjs.org/)), чтобы было больше возможностей редактирования. Ну и это будет уже готовая компонента, поэтому дизайн остальной формы нужно немножко под нее подогнать. Они в основном все примерно одинаково выглядят: белый, непрозрачный фон. Можешь погуглить что-то вроде [этого](https://www.google.com/search?q=react+markdown+editor&rlz=1C1GCEU_ruBY828BY828&oq=react+markdown+editor&aqs=chrome.0.69i59j69i60j0l4.2274j0j7&sourceid=chrome&ie=UTF-8).

**Comment by r-karol** [comment]
Слева необязательно что-то располагать. Например, можно сделать так чтобы статьи занимали 70-80% экрана, располагались по центру, а по бокам ничего не было. Или какой-нибудь фон добавить. Вот как на [Medium](https://medium.com), например. Если там любую статью открыть и вниз промотать - увидишь о чем я говорю.

**Comment by r-karol** [comment]
Что думаете?
![photo_2019-01-29_19-37-42](https://user-images.githubusercontent.com/17727164/51924081-6f267480-23fd-11e9-84dd-eb261ebf6fa0.jpg)

**Comment by r-karol** [comment]
Я думаю раздел "Популярные" пока не стоит добавлять. Когда дойдет до того что действительно будут более популярные и менее - тогда и добавим. Сразу добавлять нет смысла, мне кажется.

**Comment by ViktarDunayeu** [comment]
черно-белый минимализм - путь к успеху, условный Medium выглядит приятно, хотя как я понял там хэдер-футер и один класс - контент , максимально простой по оформлению
посмотрю еще какие формы мне подойдут, чтобы было +- стандартизировано

**Comment by r-karol** [comment]
Ну, черно-белый - это совсем необязательно. Но тренд действительно на более нейтральные цвета и на небольшую палитру.

**Comment by ViktarDunayeu** [comment]
https://yapx.ru/v/DQZIy
что-нибудь такое?

**Comment by r-karol** [comment]
Так посовременнее.
P.S. у тебя есть акичи в твиттере и фейсбуке?

**Comment by ViktarDunayeu** [comment]
по два аккаунта на каждую соц.сеть. 😐
